import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { LoadingSpinner } from "../components";
import { useAuth } from "../lib/context";
import styles from "../styles/Home.module.css";

export default function Home() {
	const { user, loading } = useAuth();
	const router = useRouter();
	if (loading) {
		return <LoadingSpinner />;
	} else if (user) {
		router.push("/dashboard", undefined, { shallow: true });
	} else {
		return (
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={styles.main}>
					<h1 className="text-3xl font-bold underline">
						Hello there from timezoner
					</h1>
				</main>

				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{" "}
						<span className={styles.logo}>
							<Image
								src="/vercel.svg"
								alt="Vercel Logo"
								width={72}
								height={16}
							/>
						</span>
					</a>
				</footer>
			</div>
		);
	}
}
